version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.11.3.23
    container_name: clickhouse
    restart: always
    environment:
      - CLICKHOUSE_DB=vemetric
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./config/config.xml:/etc/clickhouse-server/config.d/logging.xml
      - ./config/user-config.xml:/etc/clickhouse-server/users.d/logging.xml
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9363:9363'
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
