name: PR Checks

on:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: pnpm i && bun i

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
