name: Update Bot and Referrer Data

on:
  schedule:
    # Run at 2 AM UTC on the 1st of every month
    - cron: '0 2 1 * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm i && bun i

      - name: Fetch bots data (hub)
        working-directory: ./apps/hub
        run: pnpm fetch-bots && pnpm format

      - name: Fetch referrers data (worker)
        working-directory: ./apps/worker
        run: pnpm fetch-referrers && pnpm format

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update bot and referrer data'
          title: 'chore: update bot and referrer data'
          body: |
            ## Automated Monthly Update

            This PR updates the bot and referrer detection data from upstream sources:
            - Bot data from [Matomo Device Detector](https://github.com/matomo-org/device-detector)
            - Referrer data from [Snowplow Referer Parser](https://github.com/snowplow-referer-parser/referer-parser)

            This is an automated update that runs monthly to keep our detection data up-to-date.
          branch: automated/update-bot-referrer-data
          delete-branch: true
          labels: |
            automated
            dependencies
